# Generated by Django 4.2.25 on 2025-11-04 09:10

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('action', models.CharField(default='backup', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, max_length=250)),
                ('account_no', models.DecimalField(blank=True, decimal_places=0, max_digits=25, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=50)),
                ('scheme_name', models.CharField(blank=True, max_length=250)),
                ('bank_manager_name', models.CharField(blank=True, max_length=50)),
                ('bank_contact', models.CharField(blank=True, max_length=50)),
                ('bank_address', models.CharField(blank=True, max_length=250)),
                ('remark', models.CharField(blank=True, max_length=300)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('contractor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(max_length=250)),
                ('contractor_address', models.CharField(blank=True, max_length=300)),
                ('contractor_contact_no', models.CharField(blank=True, max_length=50)),
                ('contractor_pan', models.CharField(blank=True, max_length=50)),
                ('contractor_tan', models.CharField(blank=True, max_length=50)),
                ('contractor_gst', models.CharField(blank=True, max_length=50)),
                ('contractor_bank_ac', models.CharField(blank=True, max_length=50)),
                ('contractor_ifsc', models.CharField(blank=True, max_length=50)),
                ('contractor_bank', models.CharField(blank=True, max_length=50)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_name', models.CharField(blank=True, max_length=50)),
                ('district_name', models.CharField(blank=True, max_length=50)),
                ('session', models.CharField(blank=True, max_length=50)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('notice_date_111', models.CharField(blank=True, max_length=50)),
                ('issue_date', models.CharField(blank=True, max_length=50)),
                ('renewal_date', models.CharField(blank=True, max_length=50)),
                ('assessment_year', models.CharField(blank=True, max_length=50)),
                ('notice_date_120', models.CharField(blank=True, max_length=50)),
                ('age', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('tx_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=6)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('account', models.CharField(blank=True, max_length=50)),
                ('particular', models.CharField(blank=True, max_length=250)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bankaccount')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('credit_payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('received_from', models.CharField(blank=True, max_length=250)),
                ('deposit_to_account', models.CharField(blank=True, max_length=250)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('account', models.CharField(blank=True, max_length=50)),
                ('particular', models.CharField(blank=True, max_length=250)),
                ('remark', models.CharField(blank=True, max_length=250)),
                ('update_by', models.IntegerField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('payment_deposit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Clerk'), (3, 'Viewer')], default=2)),
                ('status', models.CharField(default='active', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
