# Generated by Django 4.2.25 on 2025-11-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_bank_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contractor_display_name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
