# Generated by Django 4.2.25 on 2025-11-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction_contractor_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('snapshot_id', models.AutoField(primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('scope', models.CharField(blank=True, default='all', max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bankaccount')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contractor')),
            ],
        ),
    ]
