# Generated by Django 4.2.25 on 2025-11-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_add_user_contact'),
        ('app', '0004_balancesnapshot'),
    ]

    operations = [
    ]
